<a href="https://colab.research.google.com/github/ks-yahagi/ks-yahagi/blob/main/Numpy%E3%81%AE%E5%9F%BA%E7%A4%8E.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
#Numpyのインポート

#Numpyライブラリの読み込み
import numpy as np

#少数第3位まで表示という意味
%precision 3

#配列操作

#配列の作成
data = np.array([9,2,3,4,10,6,7,8,1,5])
data

#データ型

#データの型
data.dtype

#次元数と要素数
print('次元数:',data.ndim)
print('要素数:',data.size)

#すべての要素に対する計算

#それぞれの数字を係数倍(ここでは2倍)
data *2

#それぞれの要素同士での計算
print('掛け算:',np.array([1,2,3,4,5,6,7,8,9,10])*np.array([10,9,8,7,6,5,4,3,2,1]))
print('累乗:',np.array([1,2,3,4,5,6,7,8,9,10])**2)
print('割り算:',np.array([1,2,3,4,5,6,7,8,9,10])/np.array([10,9,8,7,6,5,4,3,2,1]))

#現在の値を表示
print('そのまま:',data)

#ソートした結果を表示
data.sort()
print('ソート後:',data)

print(data)

data[::-1].sort()
print('ソート後:',data)

#最小値
print('Min:',data.min())
#最大値
print('Max:',data.max())
#合計
print('Sum:',data.sum())
#積み上げ
print('Cum:',data.cumsum())
#積み上げ割合
print('Ratio:',data.cumsum()/data.sum())

#乱数
import numpy.random as random

#乱数のシード
random.seed(0)

#正規分布(平均0, 分散1)の乱数を10個発生
rnd_data = random.randn(10)

print('乱数の10個の配列:', rnd_data)

#抽出対称データ
data = np.array([9,2,3,4,10,6,7,8,1,5])

#ランダム抽出
#10個を抽出(重複あり, 復元抽出)
print(random.choice(data,10))

#10個を抽出(重複無し, 非復元抽出)
print(random.choice(data,10, replace=False))

#Columm_Numpyは高速

#Nは乱数の発生数, 10の6乗
N = 10**6

#Python版(以下のrange(N)は0からN-1までの整数を用意しています.)
#「_」は, 代入した値を参照しないときに使う慣例的な変数名です.
#たとえば, for a in range(N)と書くのと同じですが, aと書くと, その値を後で使うように見えるので, 
#その値を参照しないときは, for _ in range(N)のように慣例的に書く書き方です
normal_data=[random.random() for _ in range(N)]

#Numpy版
numpy_random_data = np.array(normal_data)

#calc time:合計値
#普通の処理
%timeit sum(normal_data)

#Numpyを使った処理
%timeit np.sum(numpy_random_data)

'''2-2　4行列'''
np.arange(9)
array1 = np.arange(9).reshape(3,3)
print(array1)

#1行目
array1[0,:]

#1列目
array1[:,0]

array2 = np.arange(9,18).reshape(3,3)
print(array2)

#行列の計算
np.dot(array1,array2)

#要素同士の積
array1*array2

print(np.zeros((2,3),dtype=np.int64))
print(np.ones((2,3),dtype=np.float64))

次元数: 1
要素数: 10
掛け算: [10 18 24 28 30 30 28 24 18 10]
累乗: [  1   4   9  16  25  36  49  64  81 100]
割り算: [ 0.1    0.222  0.375  0.571  0.833  1.2    1.75   2.667  4.5   10.   ]
そのまま: [ 9  2  3  4 10  6  7  8  1  5]
ソート後: [ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
ソート後: [10  9  8  7  6  5  4  3  2  1]
Min: 1
Max: 10
Sum: 55
Cum: [10 19 27 34 40 45 49 52 54 55]
Ratio: [0.182 0.345 0.491 0.618 0.727 0.818 0.891 0.945 0.982 1.   ]
乱数の10個の配列: [ 1.764  0.4    0.979  2.241  1.868 -0.977  0.95  -0.151 -0.103  0.411]
[ 7  8  8  1  2  6  5  1  5 10]
[10  2  7  8  3  1  6  5  9  4]
100 loops, best of 5: 5.45 ms per loop
1000 loops, best of 5: 342 µs per loop
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
